# Generated by Django 2.0.7 on 2018-07-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('experiencias', models.TextField()),
                ('cargo', models.TextField()),
                ('pretensao_salarial', models.DecimalField(decimal_places=3, max_digits=10)),
                ('observacao', models.TextField()),
            ],
        ),
    ]
