# Generated by Django 2.0.7 on 2018-07-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='experiencias',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='candidato',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='candidato',
            name='pretensao_salarial',
            field=models.DecimalField(decimal_places=3, default='', max_digits=6),
        ),
        migrations.AddField(
            model_name='candidato',
            name='sobrenome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cargo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='observacao',
            field=models.TextField(default=''),
        ),
    ]
