# Generated by Django 2.0.7 on 2018-07-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculos', '0002_auto_20180710_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='pretensao_salarial',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
