# Generated by Django 2.0.7 on 2018-07-11 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculos', '0003_auto_20180710_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='pretensao_salarial',
        ),
    ]
